site_name: Documentation utilisateur ISTEX
pages:
- Accueil: index.md
- Configurer votre Discovery Tool: discovery.md
theme: readthedocs
docs_dir: doc/docs
site_dir: public/documentation
theme_dir: doc/istex_theme