site_name: Documentation utilisateur ISTEX
pages:
- Accueil: index.md
- Configurer votre Discovery Tool: discovery.md
- Configurer votre Logiciel de Gestion Bibliographique: logiciel.md
theme: readthedocs
docs_dir: docs
site_dir: public/documentation
theme_dir: istex_theme
