site_name: Documentation utilisateur LODEX
pages:
- Accueil: index.md
- Formats: formats.md
- Exporters: exporters.md
- Fields: fields.md
- Transformers: transformers.md
theme: readthedocs
docs_dir: docs
site_dir: public/documentation
extra_javascript:
  - //content-delivery.istex.fr/web-header/main.js
extra_css:
  - css/docs.css